
  omit('EndDefine',_Plugware_API_WINERR_)
_Plugware_API_WINERR_ equate(1)

ERROR_SUCCESS_PW           equate(0)
NO_ERROR_PW                equate(0)

ERROR_MORE_DATA_PW         equate(234)
ERROR_NO_MORE_ITEMS_PW     equate(259)

REGDB_E_CLASSNOTREG_PW     equate(080040154h)
REGDB_E_READREGDB_PW       equate(080040150h)
CO_E_DLLNOTFOUND_PW        equate(0800401F8h)	! #define CO_E_DLLNOTFOUND                 _HRESULT_TYPEDEF_(0x800401F8L)
CO_E_APPNOTFOUND_PW        equate(0800401F5h)
CO_E_ERRORINDLL_PW         equate(0800401F9h)
CO_E_APPDIDNTREG_PW        equate(0800401FEh)


  EndDefine
